#source 'https://github.com/CocoaPods/Specs.git'





platform = :osx, "10.8"

target 'TeamTalk' do
  use_frameworks!
  inhibit_all_warnings!

pod 'FMDB', '~> 2.3'
pod "AFNetworking", "~> 2.5.0"
pod 'ProtocolBuffers', '~> 1.9.4'

end