
platform :ios, '9.0'

target 'TeamTalk' do
  use_frameworks!
  inhibit_all_warnings!

pod 'FMDB', '~> 2.3'
pod 'SDWebImage', '~> 5.8.3'
pod 'AFNetworking', '~> 2.3.0'
pod 'DACircularProgress', '~> 2.2.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'PSTCollectionView', '~> 1.2.1'
pod 'HPGrowingTextView' , '~> 1.1'
pod 'ProtocolBuffers', '~> 1.9.4'
pod 'SCLAlertView-Objective-C', '~> 0.7.3'
pod 'MWPhotoBrowser'
pod 'Masonry'
pod 'TTTAttributedLabel'
pod 'SVWebViewController'
pod 'XHImageViewer'
pod 'ZXingObjC'

end
